export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: "Power & Protection" | "Fans & Cooling" | "Water Automation" | "Security & Access" | "Smart Lighting" | "Kitchen Essentials";
  serviceLink: string[];
  rating?: number;
  reviewCount?: number;
  badge?: "Best Seller" | "New" | "Hot Deal" | "Essential";
  stock?: number;
  sourceOrigin?: string;
  warrantyMonths?: number;
}

export const PRODUCTS: Product[] = [
  // ── Power & Inverter Protection ─────────────────────────────
  {
    id: "sp-power-1",
    name: "Tuya 16A Smart WiFi Energy Monitor & Surge Plug",
    description: "Real-time electricity tracking on your phone. Automatic high/low voltage surge cut-off to protect refrigerators, deep freezers, and inverter batteries. Set schedules and timers from anywhere.",
    price: 8500,
    image: "/products/extension-board.jpg",
    category: "Power & Protection",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 340,
    badge: "Best Seller",
    stock: 120,
    sourceOrigin: "Dongguan Precision Power Labs",
    warrantyMonths: 12,
  },
  {
    id: "sp-power-5",
    name: "Luxury Tempered Glass Smart WiFi In-Wall Socket (13A/16A) with Dual USB",
    description: "Modern crystal glass wall socket with independent smartphone app control, countdown timers, child safety shutter, and dual fast-charging USB ports. Directly replaces standard 13A wall sockets in bedrooms and parlours.",
    price: 13500,
    image: "/products/touch-switch-single.png",
    category: "Power & Protection",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 220,
    badge: "Best Seller",
    stock: 70,
    sourceOrigin: "Wenzhou Smart Electricals",
    warrantyMonths: 24,
  },
  {
    id: "sp-power-8",
    name: "Heavy-Duty 20A Smart WiFi Wall Switch & Socket (for AC & Water Heaters)",
    description: "Dedicated high-load 20A smart wall switch designed for 1.5HP-2HP Air Conditioners and Water Heaters. Schedule automatic morning water heating and monitor heavy electricity consumption directly on your phone.",
    price: 17500,
    image: "/products/smart-switch.jpg",
    category: "Power & Protection",
    serviceLink: ["Electrician", "AC & Fridge Repair", "Plumber"],
    rating: 4.8,
    reviewCount: 165,
    badge: "Essential",
    stock: 45,
    sourceOrigin: "Dongguan Heavy Power Labs",
    warrantyMonths: 24,
  },
  {
    id: "sp-power-6",
    name: "40,000mAh Smart Super-Fast Power Bank with Digital Display & 65W PD (Laptop + Phone)",
    description: "Heavy-duty everyday power bank built for Nigerian power cuts. 65W Type-C fast-charging powers laptops (MacBook, HP, Dell), iPhones, Android, and WiFi routers with real-time battery percentage LED screen and built-in flashlight.",
    price: 28500,
    image: "/products/smart-power-bank.jpg",
    category: "Power & Protection",
    serviceLink: ["General Handyman"],
    rating: 4.9,
    reviewCount: 480,
    badge: "Best Seller",
    stock: 85,
    sourceOrigin: "Shenzhen High-Capacity Battery Labs (Grade A Lithium Polymer)",
    warrantyMonths: 12,
  },
  {
    id: "sp-power-7",
    name: "Mini Smart Inverter UPS Power Bank for WiFi Routers & Fiber Modems (12V/9V/5V)",
    description: "Zero-delay uninterruptible power supply for home WiFi routers, fiber ONT modems, and CCTV cameras. Keeps internet and remote work running seamlessly for up to 8-10 hours during NEPA power outages.",
    price: 16500,
    image: "/products/circuit-breaker.png",
    category: "Power & Protection",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.9,
    reviewCount: 310,
    badge: "Essential",
    stock: 60,
    sourceOrigin: "Shenzhen Network Power Labs",
    warrantyMonths: 12,
  },
  {
    id: "sp-power-2",
    name: "Tuya Smart WiFi 4-Way Extension Board with 4 Fast USB Ports",
    description: "4 independent smart outlets and 4 high-speed USB ports with 16A heavy-duty surge protection. Control your TV, soundbar, laptop, and phone chargers independently via mobile app.",
    price: 18500,
    image: "/products/extension-board.jpg",
    category: "Power & Protection",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.8,
    reviewCount: 215,
    badge: "Essential",
    stock: 55,
    sourceOrigin: "Shenzhen IoT Power Hub",
    warrantyMonths: 12,
  },
  {
    id: "sp-power-3",
    name: "Smart DIN-Rail Prepaid Energy Meter & Auto-Changeover Switch",
    description: "Track total kWh consumption on your distribution board directly on your smartphone. Features remote disconnect, overload protection, and automated NEPA to generator/inverter monitoring.",
    price: 26500,
    image: "/products/circuit-breaker.png",
    category: "Power & Protection",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 168,
    badge: "Hot Deal",
    stock: 35,
    sourceOrigin: "Wenzhou Smart Grid Engineering",
    warrantyMonths: 24,
  },
  {
    id: "sp-power-4",
    name: "Digital Fridge & TV Automatic Voltage Protector (5-Min Delay)",
    description: "Heavy-duty voltage guard with built-in 3-minute startup delay to prevent compressor burnout from sudden NEPA flashes, brownouts, and dangerous power surges.",
    price: 9500,
    image: "/products/circuit-breaker.png",
    category: "Power & Protection",
    serviceLink: ["Electrician", "AC & Fridge Repair"],
    rating: 4.8,
    reviewCount: 194,
    badge: "Essential",
    stock: 80,
    sourceOrigin: "Guangdong Power Protection Co.",
    warrantyMonths: 12,
  },

  // ── Fans & Cooling ──────────────────────────────────────────
  {
    id: "sp-cool-1",
    name: "Zenith 16\" Smart Solar Rechargeable Pedestal Fan",
    description: "Essential rechargeable standing fan with built-in backup battery (up to 12 hours run time), digital LED speed display, USB mobile charging port, remote control, and optional solar panel input.",
    price: 38000,
    image: "/products/rechargeable-fan.jpg",
    category: "Fans & Cooling",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.9,
    reviewCount: 420,
    badge: "Best Seller",
    stock: 45,
    sourceOrigin: "Zenith Air Innovations (Grade A Battery)",
    warrantyMonths: 12,
  },
  {
    id: "sp-cool-2",
    name: "Tuya Smart WiFi Universal IR Remote & Climate Hub (LCD Display)",
    description: "3-in-1 universal smart controller. Controls any Air Conditioner (Hisense, LG, Panasonic, Samsung, Gree), TV, DSTV/GOTV decoder, and standing fan directly from your smartphone. Built-in LCD screen displays real-time room temperature and humidity with automatic AC cooling triggers.",
    price: 14500,
    image: "/products/smart-ir-remote.jpg",
    category: "Fans & Cooling",
    serviceLink: ["AC & Fridge Repair", "Electrician"],
    rating: 4.8,
    reviewCount: 310,
    badge: "Essential",
    stock: 65,
    sourceOrigin: "Tuya Smart IoT Labs (Model S09)",
    warrantyMonths: 12,
  },
  {
    id: "sp-cool-3",
    name: "Lontor-Grade 18\" Solar Rechargeable Mist Standing Fan with Remote",
    description: "Heavy-duty 18-inch rechargeable fan with ultra-fine water mist cooling, 9-speed digital control, USB emergency power bank port, night LED lamp, and solar panel charging input for long power cuts.",
    price: 48000,
    image: "/products/rechargeable-fan.jpg",
    category: "Fans & Cooling",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.9,
    reviewCount: 185,
    badge: "Hot Deal",
    stock: 25,
    sourceOrigin: "Lontor-Grade Solar Cooling Co.",
    warrantyMonths: 12,
  },

  // ── Water & Tank Automation ─────────────────────────────────
  {
    id: "sp-water-1",
    name: "Smart Automatic Water Tank Pumping Machine Controller",
    description: "Automatic borehole and overhead GP tank water level manager. Automatically switches on your pumping machine when the water level is low and turns it off before it overflows. Prevents dry pump damage.",
    price: 28000,
    image: "/products/circuit-breaker.png",
    category: "Water Automation",
    serviceLink: ["Plumber", "Electrician"],
    rating: 4.9,
    reviewCount: 175,
    badge: "Best Seller",
    stock: 30,
    sourceOrigin: "Zhejiang Water Flow Control Labs",
    warrantyMonths: 24,
  },
  {
    id: "sp-water-2",
    name: "Tuya Smart WiFi Flood & Water Leak Alarm Probe",
    description: "Instant phone alert and loud buzzer when water overflow or leakage is detected around kitchen sinks, washing machines, or water tanks. Prevent expensive ceiling and room flooding.",
    price: 11500,
    image: "/products/waste-pipe.png",
    category: "Water Automation",
    serviceLink: ["Plumber", "General Handyman"],
    rating: 4.7,
    reviewCount: 98,
    badge: "New",
    stock: 50,
    sourceOrigin: "Shenzhen Security Sensor Hub",
    warrantyMonths: 12,
  },
  {
    id: "sp-water-3",
    name: "Smart Instant Tankless Digital Water Heater (Shower & Tap)",
    description: "Fast digital heating for morning showers with variable temperature touch control, anti-scalding protection, and energy-saving low power draw. Perfect for instant hot water.",
    price: 85000,
    image: "/products/smart_water_heater_1787269874318.jpg",
    category: "Water Automation",
    serviceLink: ["Plumber", "Electrician"],
    rating: 4.8,
    reviewCount: 112,
    badge: "Hot Deal",
    stock: 18,
    sourceOrigin: "Foshan Water Thermal Systems",
    warrantyMonths: 24,
  },

  // ── Security & Access ───────────────────────────────────────
  {
    id: "sp-sec-1",
    name: "Tuya Biometric AI Smart Door Lock (Fingerprint + Keypad)",
    description: "Heavy-duty smart security lock with 3D biometric fingerprint scanner, RFID card, anti-peep PIN keypad, temporary guest passcode via app, and emergency mechanical backup key.",
    price: 75000,
    image: "/products/smart-lock.jpg",
    category: "Security & Access",
    serviceLink: ["Carpenter", "Electrician", "General Handyman"],
    rating: 4.9,
    reviewCount: 310,
    badge: "Best Seller",
    stock: 28,
    sourceOrigin: "Shenzhen High-Tech Hub (Grade A Zinc Alloy)",
    warrantyMonths: 24,
  },
  {
    id: "sp-sec-2",
    name: "Solar Outdoor Motion-Sensor Security LED Floodlight (100W)",
    description: "100% solar powered compound and gate security light. Automatically turns bright when motion is detected at night. Waterproof IP65, zero electricity bills, and includes wireless remote control.",
    price: 16500,
    image: "/products/led-spotlight.png",
    category: "Security & Access",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.8,
    reviewCount: 260,
    badge: "Essential",
    stock: 75,
    sourceOrigin: "Zhongshan Solar Lighting Base",
    warrantyMonths: 12,
  },
  {
    id: "sp-sec-3",
    name: "Tuya Wireless HD WiFi Video Doorbell with Indoor Chime",
    description: "See and speak with visitors at your gate or door from anywhere on your phone. Wide-angle night vision camera, motion detection alert, and plug-in indoor chime included.",
    price: 28500,
    image: "/products/smart_video_doorbell_1787269908128.jpg",
    category: "Security & Access",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.7,
    reviewCount: 145,
    badge: "New",
    stock: 40,
    sourceOrigin: "Shenzhen Smart Security Labs",
    warrantyMonths: 12,
  },

  // ── Smart Lighting & Energy Saving ──────────────────────────
  {
    id: "sp-light-4",
    name: "Smart Emergency Rechargeable LED Inverter Bulb 15W (Stays On During Outages)",
    description: "Automatic backup LED bulb that lights up instantly when NEPA takes light, running on built-in lithium battery for 4-5 hours. Automatically recharges while regular power is active.",
    price: 5500,
    image: "/products/smart-bulb.jpg",
    category: "Smart Lighting",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 520,
    badge: "Best Seller",
    stock: 200,
    sourceOrigin: "Lumina Smart Emergency Lighting",
    warrantyMonths: 12,
  },
  {
    id: "sp-light-1",
    name: "Lumina Smart RGB + Warm/Daylight WiFi LED Light Bulb (9W)",
    description: "Low-energy inverter-friendly LED bulb. Adjust brightness from 1% to 100% to save battery power during outages, choose from 16 million colors or pure crisp white, set automated sunset timers.",
    price: 6500,
    image: "/products/smart-bulb.jpg",
    category: "Smart Lighting",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 380,
    badge: "Essential",
    stock: 140,
    sourceOrigin: "Lumina Smart Lighting Labs",
    warrantyMonths: 12,
  },
  {
    id: "sp-light-5",
    name: "Smart Infrared Motion-Sensor Energy-Saving Ceiling Light (18W)",
    description: "PIR human motion detection light that turns on automatically when someone enters hallways, staircases, or balconies and turns off when vacant. Dramatically cuts electricity consumption.",
    price: 8500,
    image: "/products/led-spotlight.png",
    category: "Smart Lighting",
    serviceLink: ["Electrician"],
    rating: 4.8,
    reviewCount: 140,
    badge: "New",
    stock: 65,
    sourceOrigin: "Zhongshan Energy-Saving Labs",
    warrantyMonths: 12,
  },
  {
    id: "sp-light-2",
    name: "Luxury Tempered Glass Smart Touch Wall Switch (2-Gang)",
    description: "Modern crystal glass touch panel with soft blue LED indicators. Control parlor and bedroom lights from your smartphone, touch panel, or voice commands. Supports no-neutral wiring.",
    price: 14500,
    image: "/products/touch-switch-double.png",
    category: "Smart Lighting",
    serviceLink: ["Electrician"],
    rating: 4.8,
    reviewCount: 195,
    badge: "Essential",
    stock: 60,
    sourceOrigin: "Wenzhou Smart Electricals",
    warrantyMonths: 24,
  },
  {
    id: "sp-light-3",
    name: "Luxury Tempered Glass Smart Touch Wall Switch (3-Gang)",
    description: "Sleek 3-button touch switch for living room, passage, and dining lighting. Scheduled timers, remote phone control, and flame-retardant safety casing.",
    price: 16500,
    image: "/products/smart-switch.jpg",
    category: "Smart Lighting",
    serviceLink: ["Electrician"],
    rating: 4.8,
    reviewCount: 172,
    badge: "Essential",
    stock: 55,
    sourceOrigin: "Wenzhou Smart Electricals",
    warrantyMonths: 24,
  },

  // ── Everyday Kitchen Essentials ─────────────────────────────
  {
    id: "sp-kitch-1",
    name: "Heavy-Duty 2L Commercial Smoothie & Pepper Blender (1500W)",
    description: "Everyday powerhouse for Nigerian kitchens. Effortlessly grinds dry beans for moi-moi and akara, hard tiger nuts, pepper, tomatoes, and smoothies in seconds. Japanese 6-leaf stainless steel blades.",
    price: 38000,
    image: "/products/smart_blender_1787269812726.jpg",
    category: "Kitchen Essentials",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 290,
    badge: "Best Seller",
    stock: 35,
    sourceOrigin: "Zhongshan Commercial Kitchen Motors",
    warrantyMonths: 18,
  },
  {
    id: "sp-kitch-2",
    name: "Smart Digital Touch Rapid Air Fryer (6.5L)",
    description: "Crispy plantain (dodo), chicken, fish, yam, and pastries with 85% less oil. Fast heating elements reduce electricity consumption, with 8 one-touch presets and non-stick easy-clean basket.",
    price: 48000,
    image: "/products/smart_air_fryer_1787269690941.jpg",
    category: "Kitchen Essentials",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 310,
    badge: "Best Seller",
    stock: 30,
    sourceOrigin: "Ningbo Small Appliances Park",
    warrantyMonths: 18,
  },
  {
    id: "sp-kitch-3",
    name: "Smart Fast-Boil Precision Temperature Kettle (1.7L)",
    description: "Double-walled anti-scald electric kettle for daily morning tea, coffee, and cooking water. Real-time LED digital temperature display and 12-hour thermal keep-warm function.",
    price: 24500,
    image: "/products/smart_kettle_1787269758777.jpg",
    category: "Kitchen Essentials",
    serviceLink: ["Electrician"],
    rating: 4.7,
    reviewCount: 140,
    badge: "Essential",
    stock: 45,
    sourceOrigin: "Guangdong Small Home Tech",
    warrantyMonths: 12,
  },
  {
    id: "sp-kitch-4",
    name: "Smart Precision Single-Burner Induction Cooktop (2100W)",
    description: "Fast, energy-efficient electric cooking with instant heat. 99 power adjustment levels, child lock, timer presets, and automatic pan-detection. Inverter-friendly power management.",
    price: 36000,
    image: "/products/smart_induction_cooktop_1787269842745.jpg",
    category: "Kitchen Essentials",
    serviceLink: ["Electrician"],
    rating: 4.8,
    reviewCount: 115,
    badge: "Hot Deal",
    stock: 25,
    sourceOrigin: "Shunde Precision Cookware Labs",
    warrantyMonths: 18,
  },
  {
    id: "sp-kitch-5",
    name: "Tuya Smart WiFi LPG Gas Leak Detector & Auto Valve Shut-off Motor",
    description: "Life-saving kitchen safety. Detects cooking gas leakage immediately, triggers an 85dB siren, pushes high-priority phone alerts, and mechanically twists the gas cylinder valve closed automatically.",
    price: 38000,
    image: "/products/smart-gas-detector.jpg",
    category: "Kitchen Essentials",
    serviceLink: ["Electrician", "Plumber"],
    rating: 5.0,
    reviewCount: 420,
    badge: "Best Seller",
    stock: 60,
    sourceOrigin: "Shenzhen Smart Security Labs",
    warrantyMonths: 24,
  },

  // ── High-Efficiency Power Automation ────────────────────────
  {
    id: "sp-power-9",
    name: "Tuya 63A Smart Din-Rail Circuit Breaker & Energy Management Switch",
    description: "Installs directly inside your main DB board. Remote kill-switch for heavy ACs and water heaters from your phone before turning on the generator. Real-time kWh electricity cost metering.",
    price: 55000,
    image: "/products/smart-din-breaker.jpg",
    category: "Power & Protection",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 280,
    badge: "Essential",
    stock: 40,
    sourceOrigin: "Wenzhou Heavy Power Grid Co.",
    warrantyMonths: 24,
  },

  // ── Advanced Water Management ──────────────────────────────
  {
    id: "sp-water-5",
    name: "Smart Ultrasonic Overhead Water Tank Level Monitor & Mobile Gauge",
    description: "Zero climbing of high GP tanks. High-precision ultrasonic sensor measures tank depth from 0.5m to 15m and shows live 0-100% water percentage on your phone with low/full tank alerts.",
    price: 49500,
    image: "/products/smart-water-level.jpg",
    category: "Water Automation",
    serviceLink: ["Plumber", "Electrician"],
    rating: 4.9,
    reviewCount: 195,
    badge: "Best Seller",
    stock: 35,
    sourceOrigin: "Ningbo Flow Automation Park",
    warrantyMonths: 24,
  },
  {
    id: "sp-water-6",
    name: "Smart Touchless Infrared Faucet Adapter for Kitchen & Bathroom",
    description: "Converts any standard tap into an automatic motion-sensing tap in 30 seconds. Double sensor modes (instant wave & continuous flow). USB rechargeable battery lasts 9 months per charge.",
    price: 24500,
    image: "/products/smart-touchless-faucet.jpg",
    category: "Water Automation",
    serviceLink: ["Plumber"],
    rating: 4.8,
    reviewCount: 160,
    badge: "Hot Deal",
    stock: 50,
    sourceOrigin: "Foshan Precision Sanitary Co.",
    warrantyMonths: 12,
  },

  // ── High-Security & Biometrics ──────────────────────────────
  {
    id: "sp-sec-5",
    name: "Solar-Powered 4G/WiFi 360° Outdoor PTZ Security Camera & Floodlight",
    description: "100% wireless security that runs 24/7 on its own solar panel and backup battery without NEPA. Full-color night vision, human motion detection, siren alarm, and 2-way audio intercom.",
    price: 82000,
    image: "/products/smart-solar-cctv.jpg",
    category: "Security & Access",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 310,
    badge: "Best Seller",
    stock: 25,
    sourceOrigin: "Hangzhou Vision Smart Tech",
    warrantyMonths: 24,
  },
  {
    id: "sp-sec-6",
    name: "Smart Biometric Fingerprint & Keypad Door Handle Lock",
    description: "Keyless entry for bedrooms, masters, and offices. Fast 0.3s semiconductor fingerprint scanner, PIN keypad, IC cards, and mechanical emergency backup key. Replaces standard door locks effortlessly.",
    price: 68000,
    image: "/products/smart-door-handle-lock.jpg",
    category: "Security & Access",
    serviceLink: ["Carpenter", "General Handyman"],
    rating: 4.9,
    reviewCount: 240,
    badge: "Essential",
    stock: 30,
    sourceOrigin: "Zhongshan Lock Manufacturing Hub",
    warrantyMonths: 24,
  },

  // ── Health & Food Preservation ──────────────────────────────
  {
    id: "sp-light-6",
    name: "Solar Rechargeable Smart UV Mosquito & Flying Insect Trap Lamp",
    description: "Dual-mode bionic 365nm UV light that lures and eliminates mosquitoes and flies silently. Solar + USB rechargeable, waterproof for balconies, corridors, bedrooms, and compounds.",
    price: 18500,
    image: "/products/smart-mosquito-trap.jpg",
    category: "Smart Lighting",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.7,
    reviewCount: 380,
    badge: "Hot Deal",
    stock: 80,
    sourceOrigin: "Zhongshan EcoLighting Labs",
    warrantyMonths: 12,
  },
  {
    id: "sp-cool-4",
    name: "Smart Deep Freezer & Refrigerator Wireless Temperature Alert Sensor",
    description: "Saves raw meat, soup, and frozen foods from spoiling. Waterproof probe monitors freezer temp (-40°C to 80°C) and sounds a high-priority alert on your phone if temperatures rise during power outages.",
    price: 19500,
    image: "/products/smart-freezer-sensor.jpg",
    category: "Fans & Cooling",
    serviceLink: ["AC & Fridge Repair", "Electrician"],
    rating: 4.8,
    reviewCount: 155,
    badge: "Essential",
    stock: 65,
    sourceOrigin: "Shenzhen Precision Sensor Tech",
    warrantyMonths: 18,
  },
];
