export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: "Smart Security" | "Smart Climate" | "Smart Cleaning" | "Smart Lighting" | "Smart Kitchen" | "Smart Automation";
  serviceLink: string[];
  rating?: number;
  reviewCount?: number;
  badge?: "Best Seller" | "New" | "Hot Deal" | "Limited";
  stock?: number;
  sourceOrigin?: string;
  warrantyMonths?: number;
}

export const PRODUCTS: Product[] = [
  // ── Smart Security ──────────────────────────────────────────
  {
    id: "sp-1",
    name: "Tuya Biometric AI Smart Door Lock",
    description: "Multi-modal smart lock with 3D biometric fingerprint scanner, RFID card, PIN keypad, temporary visitor passcode, and mechanical backup key. Ultra-durable zinc alloy with mobile app remote unlocking.",
    price: 95000,
    image: "/products/smart-lock.jpg",
    category: "Smart Security",
    serviceLink: ["Carpenter", "Electrician", "General Handyman"],
    rating: 4.9,
    reviewCount: 248,
    badge: "Best Seller",
    stock: 24,
    sourceOrigin: "Shenzhen High-Tech Hub (Grade A OEM)",
    warrantyMonths: 24,
  },
  {
    id: "sp-2",
    name: "360° 4K Solar-Powered Smart Outdoor PTZ Camera",
    description: "Wire-free dual-lens security camera with integrated monocrystalline solar panel. Humanoid AI auto-tracking, color night vision, siren alarm, and 2-way real-time audio.",
    price: 48000,
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=800",
    category: "Smart Security",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.8,
    reviewCount: 189,
    badge: "Hot Deal",
    stock: 35,
    sourceOrigin: "Hangzhou IoT Tech (ISO9001 Certified)",
    warrantyMonths: 12,
  },
  {
    id: "sp-3",
    name: "Tuya HD WiFi Video Doorbell & Chime",
    description: "1080p wide-angle camera doorbell with PIR motion detection, instant smartphone chime push notifications, infrared night vision, and tamper alarm.",
    price: 32000,
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=800",
    category: "Smart Security",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.7,
    reviewCount: 112,
    badge: "New",
    stock: 40,
    sourceOrigin: "Shenzhen Smart Hardware Labs",
    warrantyMonths: 12,
  },

  // ── Smart Cleaning ──────────────────────────────────────────
  {
    id: "sp-4",
    name: "Laser LiDAR 4000Pa Smart Robot Vacuum & Mop",
    description: "360° LiDAR LDS laser mapping, 4000Pa hurricane suction, and ultrasonic carpet detection. Auto-recharges, resume cleaning, and customizable no-go zones via mobile app.",
    price: 185000,
    image: "https://images.unsplash.com/photo-1618090584126-129cd1f3fabb?auto=format&fit=crop&q=80&w=800",
    category: "Smart Cleaning",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.9,
    reviewCount: 94,
    badge: "Best Seller",
    stock: 12,
    sourceOrigin: "Suzhou Robotics Precision (CE / RoHS Certified)",
    warrantyMonths: 24,
  },
  {
    id: "sp-5",
    name: "Smart Motion-Sensor Touchless Trash Bin (16L)",
    description: "0.3s quick-open infrared wave sensor dustbin with automatic bag sealing, odor-lock airtight lid, and stainless steel fingerprint-resistant coating.",
    price: 24500,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=800",
    category: "Smart Cleaning",
    serviceLink: ["General Handyman"],
    rating: 4.6,
    reviewCount: 78,
    stock: 50,
    sourceOrigin: "Guangdong Smart Appliance Park",
    warrantyMonths: 12,
  },

  // ── Smart Climate ───────────────────────────────────────────
  {
    id: "sp-6",
    name: "Smart H13 True-HEPA Air Purifier & PM2.5 Monitor",
    description: "CADR 400m³/h high-efficiency air purifier removing 99.97% of airborne dust, smoke, and allergens. Built-in OLED digital air quality screen with whisper-quiet 24dB sleep mode.",
    price: 88000,
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&q=80&w=800",
    category: "Smart Climate",
    serviceLink: ["AC & Fridge Repair", "Electrician"],
    rating: 4.9,
    reviewCount: 143,
    badge: "Hot Deal",
    stock: 18,
    sourceOrigin: "Foshan Climate Tech (Global Export Grade)",
    warrantyMonths: 24,
  },
  {
    id: "sp-7",
    name: "Tuya WiFi Universal Smart IR Blaster & AC Controller",
    description: "Consolidate all air conditioner, TV, and fan remotes into your phone. Built-in temperature and humidity LCD screen with intelligent automation triggers.",
    price: 18500,
    image: "https://images.unsplash.com/photo-1558089687-f282ffcbc126?auto=format&fit=crop&q=80&w=800",
    category: "Smart Climate",
    serviceLink: ["AC & Fridge Repair", "Electrician"],
    rating: 4.7,
    reviewCount: 215,
    badge: "Best Seller",
    stock: 65,
    sourceOrigin: "Shenzhen IoT Hub",
    warrantyMonths: 12,
  },
  {
    id: "sp-8",
    name: "Smart Ultrasonic Mist Aromatherapy Humidifier (4L)",
    description: "App-controlled cool mist ultrasonic humidifier with RGB mood lighting, auto shut-off, and scheduling to maintain ideal home humidity in dry air conditions.",
    price: 26000,
    image: "https://images.unsplash.com/photo-1608848461950-0fe51dfc41cb?auto=format&fit=crop&q=80&w=800",
    category: "Smart Climate",
    serviceLink: ["General Handyman"],
    rating: 4.5,
    reviewCount: 62,
    stock: 30,
    sourceOrigin: "Ningbo Appliance Manufacturing",
    warrantyMonths: 12,
  },

  // ── Smart Lighting & Power ──────────────────────────────────
  {
    id: "sp-9",
    name: "Luxury Tempered Glass Smart Touch Switch (3-Gang)",
    description: "Crystal glass capacitive touch panel with soft blue LED status indicators. Capacitive no-neutral wire required option, voice control with Alexa and Google Assistant.",
    price: 16500,
    image: "/products/touch-switch-double.png",
    category: "Smart Lighting",
    serviceLink: ["Electrician"],
    rating: 4.8,
    reviewCount: 176,
    badge: "Best Seller",
    stock: 80,
    sourceOrigin: "Wenzhou Electrical Smart Labs",
    warrantyMonths: 24,
  },
  {
    id: "sp-10",
    name: "Tuya 16A Smart WiFi Energy Monitor Plug (Twin Pack)",
    description: "Track electricity consumption in real-time on your smartphone. 16A surge protection, scheduled timers, and remote shutoff for heavy home appliances.",
    price: 15000,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800",
    category: "Smart Lighting",
    serviceLink: ["Electrician"],
    rating: 4.7,
    reviewCount: 310,
    badge: "Hot Deal",
    stock: 120,
    sourceOrigin: "Dongguan Precision Electronics",
    warrantyMonths: 12,
  },
  {
    id: "sp-11",
    name: "Smart RGBIC Flowing Ambient Light Strip (10m)",
    description: "Segmented multi-color LED strip with sound reactive music sync, Bluetooth & WiFi dual connectivity, 16 million colors, and IP65 waterproof silicone coating.",
    price: 21000,
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800",
    category: "Smart Lighting",
    serviceLink: ["Electrician", "General Handyman"],
    rating: 4.6,
    reviewCount: 88,
    stock: 45,
    sourceOrigin: "Zhongshan Lighting Capital (Export Grade)",
    warrantyMonths: 12,
  },

  // ── Smart Kitchen & Water ───────────────────────────────────
  {
    id: "sp-12",
    name: "Matte Black Smart Touchless Sensor Kitchen Faucet",
    description: "Wave-activated infrared sensor faucet with 360° pull-down sprayer, dual flow modes, solid brass body, and battery-operated valve system.",
    price: 45000,
    image: "/products/water-mixer-tap.png",
    category: "Smart Kitchen",
    serviceLink: ["Plumber"],
    rating: 4.9,
    reviewCount: 130,
    badge: "Best Seller",
    stock: 22,
    sourceOrigin: "Kaiping Sanitary Ware Innovation Center",
    warrantyMonths: 36,
  },
  {
    id: "sp-13",
    name: "Tuya Smart WiFi Flood & Water Leak Detector",
    description: "Ultra-sensitive gold-plated probe detector that sends instant loud alarm and push notification to your phone when water overflow is detected under sinks, washing machines, or water heaters.",
    price: 12500,
    image: "https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&q=80&w=800",
    category: "Smart Kitchen",
    serviceLink: ["Plumber", "Electrician"],
    rating: 4.8,
    reviewCount: 95,
    badge: "New",
    stock: 60,
    sourceOrigin: "Shenzhen Security Sensor Hub",
    warrantyMonths: 12,
  },
  {
    id: "sp-14",
    name: "Smart Precision Induction Cooktop with Touch App",
    description: "2100W microcrystalline glass induction burner with 99-level precision heat tuning, timer presets, automatic cookware detection, and child lock protection.",
    price: 42000,
    image: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&q=80&w=800",
    category: "Smart Kitchen",
    serviceLink: ["Electrician"],
    rating: 4.7,
    reviewCount: 67,
    stock: 28,
    sourceOrigin: "Shunde Kitchen Appliances Base",
    warrantyMonths: 18,
  },

  // ── Smart Automation ────────────────────────────────────────
  {
    id: "sp-15",
    name: "Smart Automatic Motorized Curtain Track & Motor (3.2m)",
    description: "Silent heavy-duty electric curtain motor with expandable track. Open/close via remote control, smartphone app, voice command, or gentle manual pull trigger.",
    price: 78000,
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800",
    category: "Smart Automation",
    serviceLink: ["Carpenter", "Electrician", "General Handyman"],
    rating: 4.8,
    reviewCount: 54,
    badge: "New",
    stock: 15,
    sourceOrigin: "Hangzhou Smart Motor Technology",
    warrantyMonths: 24,
  },
  {
    id: "sp-16",
    name: "Tuya Zigbee 3.0 Smart Multi-Sensor Gateway Hub",
    description: "Universal IoT bridge connecting up to 128 smart sub-devices (locks, sensors, switches, alarms) with offline local scene automation and ultra-low power consumption.",
    price: 19500,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800",
    category: "Smart Automation",
    serviceLink: ["Electrician"],
    rating: 4.9,
    reviewCount: 160,
    badge: "Best Seller",
    stock: 55,
    sourceOrigin: "Shenzhen IoT Ecosystem Labs",
    warrantyMonths: 12,
  }
];
